<?php
/*
 * This file is part of the AjroudSoftwares/image-cropper package.
 *
 *  (c) Aymen Ajroud  <ajroudaymen@ajroudsoftwares.tn>
 *
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 */

namespace AjroudSoftwares\ImageCropperBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;


/**
 * Class ImageCropperType
 */
class ImageCropperType extends AbstractType
{
    /**
     * @param FormView $view
     * @param FormInterface $form
     * @param array $options
     * @return void
     */
    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['cropperOptions'] = $options['cropperOptions'];
        $view->vars['cropperSizeOptions'] = $options['cropperSizeOptions'];
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    /**
     * @param OptionsResolver $resolver
     * @return void
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'label' => 'Image',
            'help' => 'Double click on the image to change drag mode',
            'attr' => [
                'placeholder' => 'Image',
            ],
            'row_attr' => [
                // row_attr is not a standard option, it's a custom option that you can use to add attributes to the form row
            ],
            'required' => true,
            'constraints'=>[
                new Image(['maxSize'=>'4000k','mimeTypes'=>['image/*'],'mimeTypesMessage'=>'Veuillez choisir une image avec une taille inférieure à 4Mo'])
            ],
            // check https://github.com/fengyuanchen/cropperjs/blob/main/README.md#options for all options
            'cropperOptions'=>[
                'aspectRatio'=>16/9,
            ],
            // check https://github.com/fengyuanchen/cropperjs/blob/main/README.md#getcroppedcanvasoptions for all getCroppedCanvas() options
            'cropperSizeOptions'=>[
                'width'=>1980,
                'height'=>1020,
            ],
        ]);
    }

    /**
     * @return string
     */
    public function getParent(): string
    {
        return FileType::class;
    }
}